SERVICE:
  CHANNEL: ibm_quantum
  INSTANCE: ibm-q-nus/default/default
RUNTIME_OPTIONS:
  optimization_level: 3
  resilience_level: null
  max_execution_time: null
  transpilation:
    skip_transpilation: false
    initial_layout: null
    approximation_degree: null
    layout_method: null
    routing_method: null
  resilience:
    extrapolator: null
    noise_amplifier: null
    noise_factors: null
  environment:
    log_level: WARNING
    job_tags: null
  simulator:
    seed_simulator: 400
    coupling_map: null
    basis_gates: null
BACKEND:
  REAL_BACKEND: null
  NAME: null
  DYNAMICS:
    USE_DYNAMICS: null
    PHYSICAL_QUBITS: null
TARGET:
  GATE: CX
  PHYSICAL_QUBITS: [ 0, 1 ]

ENV:
  SAMPLING_PAULIS: 100
  N_SHOTS: 200
  C_FACTOR: 0.25
  N_ACTIONS: 7
  BATCH_SIZE: 100
  ACTION_SPACE:
    LOW: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14]
    HIGH: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]
  OBSERVATION_SPACE: 1
  BENCHMARK_CYCLE: 1
  SEED: 100
  CHECK_ON_EXP: false
  TRAINING_WITH_CAL: false