N_TRIALS: 1
N_UPDATES: 1
N_EPOCHS: 8
MINIBATCH_SIZE: [8, 16, 32, 64]
NUM_MINIBATCHES: [4, 8, 12, 16]
LR: 0.0005
N_SHOTS: 1
SAMPLE_PAULIS: [10, 25, 50, 100, 250, 500, 750, 1024]
GAMMA: 0.99 # Discount factor
GAE_LAMBDA: 0.95 # Lambda coefficient for Generalized Advantage Estimation
ENT_COEF: 0.0 # Entropy coefficient
V_COEF: 0.5 # Value (critic) function coefficient
GRADIENT_CLIP: 0.5 # Gradient clipping
CLIP_VALUE_LOSS: True # Whether to clip value loss
CLIP_VALUE_COEF: 0.2 # Clipping coefficient for value loss
CLIP_RATIO: 0.2 # Clipping ratio for PPO