N_TRIALS: 1
N_UPDATES: 1
N_EPOCHS: 8
MINIBATCH_SIZE: [4, 8, 16, 32] #, 64, 128, 256]
NUM_MINIBATCHES: [1, 2, 3, 4, 5] #, 6, 7, 8, 9, 10]
LR: 0.001
N_SHOTS: 
  - 10
  - 1000
SAMPLE_PAULIS:
  - 10
  - 150
GAMMA: 0.99 # Discount factor
GAE_LAMBDA: 0.95 # Lambda coefficient for Generalized Advantage Estimation
ENT_COEF: 0.0 # Entropy coefficient
V_COEF: 0.5 # Value (critic) function coefficient
GRADIENT_CLIP: 0.5 # Gradient clipping
CLIP_VALUE_LOSS: True # Whether to clip value loss
CLIP_VALUE_COEF: 0.2 # Clipping coefficient for value loss
CLIP_RATIO: 0.2 # Clipping ratio for PPO